# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import expressora_pb2 as expressora__pb2


class TranslationServiceStub(object):
    """Service definition for bidirectional streaming and translation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamLandmarks = channel.stream_stream(
                '/expressora.TranslationService/StreamLandmarks',
                request_serializer=expressora__pb2.LandmarkFrame.SerializeToString,
                response_deserializer=expressora__pb2.RecognitionEvent.FromString,
                )
        self.TranslateSequence = channel.unary_unary(
                '/expressora.TranslationService/TranslateSequence',
                request_serializer=expressora__pb2.GlossSequence.SerializeToString,
                response_deserializer=expressora__pb2.TranslationResult.FromString,
                )


class TranslationServiceServicer(object):
    """Service definition for bidirectional streaming and translation
    """

    def StreamLandmarks(self, request_iterator, context):
        """1. Streaming: Returns "GLOSS" (word) or "TONE" (context) events. Stateless.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranslateSequence(self, request, context):
        """2. Unary: Client sends the final list to get the sentence.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamLandmarks': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamLandmarks,
                    request_deserializer=expressora__pb2.LandmarkFrame.FromString,
                    response_serializer=expressora__pb2.RecognitionEvent.SerializeToString,
            ),
            'TranslateSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateSequence,
                    request_deserializer=expressora__pb2.GlossSequence.FromString,
                    response_serializer=expressora__pb2.TranslationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'expressora.TranslationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TranslationService(object):
    """Service definition for bidirectional streaming and translation
    """

    @staticmethod
    def StreamLandmarks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/expressora.TranslationService/StreamLandmarks',
            expressora__pb2.LandmarkFrame.SerializeToString,
            expressora__pb2.RecognitionEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TranslateSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/expressora.TranslationService/TranslateSequence',
            expressora__pb2.GlossSequence.SerializeToString,
            expressora__pb2.TranslationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
