# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: expressora.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65xpressora.proto\x12\nexpressora\"M\n\rLandmarkFrame\x12\r\n\x05hands\x18\x01 \x03(\x02\x12\x0c\n\x04\x66\x61\x63\x65\x18\x02 \x03(\x02\x12\x0c\n\x04pose\x18\x03 \x03(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\x93\x01\n\x10RecognitionEvent\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.expressora.RecognitionEvent.Type\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"+\n\x04Type\x12\t\n\x05GLOSS\x10\x00\x12\x08\n\x04TONE\x10\x01\x12\x0e\n\nHANDS_DOWN\x10\x02\"7\n\rGlossSequence\x12\x0f\n\x07glosses\x18\x01 \x03(\t\x12\x15\n\rdominant_tone\x18\x02 \x01(\t\"^\n\x11TranslationResult\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x19\n\x11sentence_filipino\x18\x02 \x01(\t\x12\x0c\n\x04tone\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t2\xb3\x01\n\x12TranslationService\x12N\n\x0fStreamLandmarks\x12\x19.expressora.LandmarkFrame\x1a\x1c.expressora.RecognitionEvent(\x01\x30\x01\x12M\n\x11TranslateSequence\x12\x19.expressora.GlossSequence\x1a\x1d.expressora.TranslationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'expressora_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LANDMARKFRAME']._serialized_start=32
  _globals['_LANDMARKFRAME']._serialized_end=109
  _globals['_RECOGNITIONEVENT']._serialized_start=112
  _globals['_RECOGNITIONEVENT']._serialized_end=259
  _globals['_RECOGNITIONEVENT_TYPE']._serialized_start=216
  _globals['_RECOGNITIONEVENT_TYPE']._serialized_end=259
  _globals['_GLOSSSEQUENCE']._serialized_start=261
  _globals['_GLOSSSEQUENCE']._serialized_end=316
  _globals['_TRANSLATIONRESULT']._serialized_start=318
  _globals['_TRANSLATIONRESULT']._serialized_end=412
  _globals['_TRANSLATIONSERVICE']._serialized_start=415
  _globals['_TRANSLATIONSERVICE']._serialized_end=594
# @@protoc_insertion_point(module_scope)
